---
resources:
- alias: state
  format: string
- alias: pumpTemperature
  format: float
- alias: flow
  format: float
- alias: pressure
  format: float
- alias: pressure2
  format: float
- alias: humidity
  format: float
